FROM eclipse-temurin:21-jre-jammy AS base-runner
FROM base-runner AS runner

LABEL authors="Marcos Henrique de Santana"
LABEL version="0.0.1-SNAPSHOT"

USER root
WORKDIR /app
COPY --chown=root:root --chmod=744 ./target/backend-chat-ai-azure-*.jar app.jar
RUN adduser apprunner

USER apprunner

ENV PATH="/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV JAVA_HOME="/opt/java/openjdk"
ENV JAVA_VM_OPTIONS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=80"

ENTRYPOINT ["bash", "-c"]
CMD ["exec java $JAVA_VM_OPTIONS -jar /app/app.jar"]

EXPOSE 8080
EXPOSE 9000
